### ISSUE TITLE
Article preview

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator#10]
View and template for an article preview in article manager.

- <del>Switch between cyrillic and latin versions</del>
- <del>Check state of article in comparison with version on dokuwiki</del>
- Log activity
- Source URL
- Get from dokuwiki
- Save to dokuwiki

Also we need to show information for:

- Title
- author (with link to author's profile) 
- status  (descriptive)

**Comment by Atlantic777** [comment]
Is this just the read-only editor?

Possible duplicate of #7

**Comment by mekanix** [comment]
We agreed to use external program to export from dokuwiki and import to liberator through API
