### ISSUE TITLE
Provisioning does not work - UnicodeDecodeError

### ISSUE THREAD

**Issue by fantastic001** [libreoss/liberator#11]
When trying to provision new machine i get the following output during vagrant up phase 

https://paste.lugons.org/show/y16unwGnVQrCxCmy4CVR/

HOW TO REPRODUCE: do `vagrant destroy -f` and then do `vagrant up` in the path where Vagrantfile is located.

**Comment by Atlantic777** [comment]
Try removing all py cache files.

**Comment by mekanix** [comment]
@fantastic001 is this solved with https://github.com/libreoss/liberator-api/commit/16690d12f715f5ac503ac94514d68306a8b7c9bd? If yes, just close the issue, please.
