### ISSUE TITLE
Tag for private notes

### ISSUE THREAD

**Issue by aleksy** [libreoss/liberator#27]
Tag to show selected text only to few people.

Such tag would display the selected text only to chosen users. For example comments made by lectors would be visible only to the editor(s). Another example is that comments made by editor could only be seen by the author.
I imagined the way it's supposed to work: selecting the text, choosing the icon and then selecting which users or user groups are allowed to see the specific text.

This feature requires the tags (it's content) to be saved in database separately from the text (article). That would ensure that the tags could be edited only by its author.

**Comment by mekanix** [comment]
This is too advanced for this stage of the project
