### ISSUE TITLE
Adapt the admin interface for the custom database models

### ISSUE THREAD

**Issue by bandigarf** [libreoss/liberator#62]
As of 46e36fb7b8fc1be40c5f9b1aa1aeff9727e0344a, the database models include a __str__ method and show some basic information (e.g. title in various languages, when available).

The admin interface should include other fields as well, not just the name/title.

See https://docs.djangoproject.com/en/1.7/intro/tutorial02/#customize-the-admin-change-list for reference.

**Comment by Atlantic777** [comment]
This is very useful for testing purposes during development and it's not so big thing. This can be done by juniors and it's a great way for getting into touch with django, working with database and understanding current liberator db model.

Just to clarify what needs to be done: 
  - we need more usable "add <model>" forms in the admin interface
  - we wan't more columns in the table for db models in admin interface 

Here are examples:

``` Gherkin
Given you are on http://192.168.66.6:8000/admin/ 
When try adding some articles in the "Add article" admin form 
Then you should be able to add an "Article title" and "Article content" object, too. 
```
An Article object can be created without it's titles and contents' but in the most cases we want to be able to add them from one place. 

One more thing which is useful in admin interface is to add more columns to that table for a model in admin interface. Here's an example for that, too:

``` Gherkin
Given you are in the django admin interface
When you open "Article" so you can see all objects of that kind
Then you have this <column> in that table:
    | column          |
    | Article title   |
    | State           |
    | Section         |
    | Serie           |
    | Serie part      |
    | Issue           |
    | No. of titles   |
    | No. of contents |
````

This should be done for other models, too and be free to change this specification against your view how it should be done. If you're a junior, be free to assign yourself for this task and ask for help on the IRC channel.

**Comment by mekanix** [comment]
Closing, as all operations should be done through API, not admin
