### ISSUE TITLE
Support multiple Authors per Article

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator#70]
Current DB model implementation supports only one Author per Article entry and information about Author is stored in the Article model. The problem raises when more Authors are writing that Article.

Possible solution:
We can introduce new relation Authorship which is represented as model (table) which holds Author ID and Article ID. That way we can have more authors for that article.

The question is do we need transcription and Author names in multiple languages. That changes Author model alot because we need to separate Author model which has only Author ID from Author Name model in any language which relates to some Author ID.

**Comment by mekanix** [comment]
To be considered: https://docs.djangoproject.com/en/1.7/ref/models/fields/#django.db.models.ManyToManyField
