### ISSUE TITLE
Support retrieving of all title and content entries for an article

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator#79]
The #78 needs to get last revisions for title and content in every language available which relates to given article.

Example:

``` Python
article  = Article.objects.get(id=12)
titles   = article.last_titles_per_lang()
content  = article.last_content_per_lang()
```

**Comment by bandigarf** [comment]
To me, *last_titles_per_lang* and *last_content_per_lang* just look ugly and I would prefer to have methods like this:

```python
def title(self, revision=None):
    if revision:
        # return this specific revision
    else:
        # return the latest revision
```

Of course, we can add a *language* argument in a similar manner.

**Comment by mekanix** [comment]
Closing for now, as we don't remember older revisions anywhere. We'll create a new issue once we stabilize API
