### ISSUE TITLE
Full functionality for /articles endpoint

### ISSUE THREAD

**Issue by Atlantic777** [libreoss/liberator#83]
Support for sorting and filtering. Probably requires using `serializers.Serializer` instead of `serializers.ModelSerializer`.

**Comment by Atlantic777** [comment]
Actually, it can be done with `serializers.ModelSerializer`. Just override the `list()` and `retrieve()` methods in the viewset. In the viewset you can (based on args, request data) decide which serializer to use and how to build the queryset.

This means that decision on which format to use is moved out of serializer (which is good). We can stick to `serializers.ModelSerializer` with multiple serializers for different formats what simplifies code for each serializer (which is also good).

**Comment by mekanix** [comment]
Closing, as it takes basic frontend to figure out what to do with it
